### ISSUE TITLE
source files only

### ISSUE THREAD

**Issue by mattduffield** [jas-chen/karma-sourcemap-writer#1]
Hi Jas-Chen,

Your solution works great but I only want to configure this for my source files.  Instead I am seeing coverage for my test folder and a webpack folder.  Is there a way to only have coverage for my source files?

Thanks,

Matt

**Comment by jas-chen** [comment]
Hi @mattduffield,

I've add a description about this issue (step 7) and [the example project](https://github.com/jas-chen/karma-sourcemap-writer) was updated too, you can check it out.
