### ISSUE TITLE
Thank you!!!

### ISSUE THREAD

**Issue by FezVrasta** [jas-chen/karma-sourcemap-writer#2]
Sorry but I must say thanks for this awesome module.

I wonder why it has just 4 stars, I tried several alternatives without success, this instead works just perfectly!

Thanks so much

**Comment by jas-chen** [comment]
Hi @FezVrasta, I'm glad it helped! Don't worry about the stars 😇

**Comment by mharris717** [comment]
+1000000 for THANK YOU!!!!!

Not just for the module, but for the super helpful README that worked on the first try. You rock.
