### ISSUE TITLE
karma-sourcemap-writer is constantly invaliding the webpack bundle

### ISSUE THREAD

**Issue by lazd** [jas-chen/karma-sourcemap-writer#3]
When I have the following pre-processors, my bundle is built once:

```
['webpack', 'sourcemap', 'coverage']
```

When I add `sourcemap-writer`, it's invalidated and rebuilt 6 times, which makes the build take twice as long:

```
['webpack', 'sourcemap', 'sourcemap-writer', 'coverage']
```

I've configured my `karma.conf.js` as the repo instructed, and everything worked as normal until I added `sourcemap-writer`.

**Comment by lazd** [comment]
This issue seems to be caused by the fact that the `.map` file matches a glob and gets watched by webpack. I'm exploring how to write this map file to a different location in a fork.

**Comment by lazd** [comment]
This issue seems to be caused by the fact that the `.map` file matches a glob and gets watched by webpack. I'm exploring how to write this map file to a different location in a fork.

**Comment by lazd** [comment]
This issue seems to be caused by the fact that the `.map` file matches a glob and gets watched by webpack. I'm exploring how to write this map file to a different location in a fork.

**Comment by lazd** [comment]
Unfortunately, this process is too convoluted to use in our project and we'll be looking for another means of accomplishing the same task.

**Comment by lazd** [comment]
For those interested, here's how I got code coverage working nicely without using `remap-istanbul` or `karma-sourcemap-writer`.

In `webpack.config.js`:

``` js
{
  module: {
    postLoaders: [
      {
        include: /scripts\//, // Include only files within the scripts/ folder
        test: /\.js$/,
        loader: 'istanbul-instrumenter'
      }
    ]
  },
  devtool: 'inline-source-map' // Generate sourcemaps
}
```

In `karma.conf.js`:

``` js
{
  preprocessors: {
    'tests/*.js': ['webpack', 'coverage']
  },
  reporters: ['progress', 'coverage'],
  coverageReporter: {
    type: 'lcov',
    dir: 'build/coverage/'
  }
}
```

In `tests/index.js`:

``` js
var testsContext = require.context('.', false, /test/); // load all files with "test" in the name
testsContext.keys().forEach(testsContext);
```

Though the result still contains coverage from the bundle, I can still view coverage for the subdirectory, `scripts/` that contains the files I'm testing.

Big thanks to @pablolmiranda for his comment https://github.com/webpack/karma-webpack/issues/21#issuecomment-113308806 detailing how he accomplished this. I simply adapted what he did for our use case and it was much simpler than using `remap-istanbul` and this repo.

**Comment by jas-chen** [comment]
@lazd thank you for your information!
